language: c

compiler:
    - gcc

install:
    - sudo apt-get -qqy update
    - sudo apt-get -qqy install check valgrind wget
    - mkdir $HOME/checksrc
    - cd $HOME/checksrc
    - wget http://micah.cowan.name/projects/checkmk/checkmk-1.0.0pre4.tar.gz
    - tar -xvzf checkmk-1.0.0pre4.tar.gz
    - cd checkmk-1.0.0pre4/
    - ./configure --prefix=$HOME/checksrc
    - make
    - make install
    - export PATH=$PATH:$HOME/checksrc/bin
    - cd $TRAVIS_BUILD_DIR

script:
    - make -f Makefile.bootstrap
    - ./configure
    - make
    - cd tests
    - make
    - make test
    - gcov ./test_stats
    - cat test_stats.check.gcov
    - valgrind --leak-check=full ./test_stats
